### PR TITLE
Renovated Project

### PR DESCRIPTION
**Pull request by amanuel2**
First of all, the comment above was unnececary and error prone. Second of all converted this proejected to a library

### CODE REVIEW

**Comment by jdc20181** [comment]
The Comment is for license reasons I cannot have it posted without it. Secondly I dont want it as a library just yet. 

I will eventually make it into this but not yet. I am focused on makijg it work. Not being Shipped out. This is just my playground and isn't intended for Non-Developers to use. The comment is also not in my code under Gh-pages branch. As I didn't think it was needed. I won't allow any pull requests in the gh-pages branch. 

So To sum it all up. I am not merging this just yet. I will eventually. But not yet. I want to work on the other parts first.

**Comment by jdc20181** [comment]
Also renaming variables isn't gonna help any. It will only slow me down, as I have to redo everything in the front end. It was nicely compact and didn't have any issues. 

What I am looking for:

-Current Processor type 

-OS

-Browser

-A way to record this data easily. 

-A Way to allow usres to change page color using this: http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_style_backgroundcolor

And 

Upload Speed.

**Comment by amanuel2** [comment]
lol your here? Arent you sleeping with your back pain lol? lol ok... its much harder

**Comment by amanuel2** [comment]
If this is not a liabary, this is useless to the community, as there are hundreds of better speed tester.. some which are just a extension but better than this(Since they code it in low level langs like C++,C,Asm,Etc..).

**Comment by jdc20181** [comment]
Yes, actually i was resting. I was looking at facebok on my phone whle laying in bed and my back stopped hurting after laying on a pillow. 

I am not worried bout it being "harder" I wrote this from a tutorial to learn xD

**Comment by amanuel2** [comment]
oh kk.. i thought it was a competeion nvm then! Sorry for interuption

**Comment by jdc20181** [comment]
I didn't say it wont be such. And idc about them. This isn't a invention or anything of the sort. This is for my playground environment I have over 50 respos, and each one of them has somethng to do with using a certain function in js. 

Also I am not here for competition, at least not yet. My rival is a Paid API service called speedof.me which is by far more complex than this, but mine is staying open source. not just during beta.

**Comment by jdc20181** [comment]
if you could add back the part with 'var oProgress = document.getElementById("progress");' as that is how it actually functions that would be great...I will add it after.

**Comment by amanuel2** [comment]
https://www.gitbook.com/book/amanuel2/ng-forum/settings/collaborators

. And if i add that, it is no longer a full library.. and i have an idea but, lol

**Comment by jdc20181** [comment]
I couldnt view link says its forbidden

**Comment by jdc20181** [comment]
ill go ahed and merge this but how the hell am i suppose to add this in the html the way i had it was easier...

**Comment by jdc20181** [comment]
to understand at least

**Comment by amanuel2** [comment]
https://www.gitbook.com/book/amanuel2/ng-forum

**Comment by amanuel2** [comment]
https://www.gitbook.com/book/amanuel2/ng-forum

**Comment by amanuel2** [comment]
https://www.gitbook.com/book/amanuel2/ng-forum

**Comment by jdc20181** [comment]
whoa bro
i already made a gitbook lol

**Comment by amanuel2** [comment]
no lol  write here when you sleep : https://www.gitbook.com/book/amanuel2/ng-forum

**Comment by amanuel2** [comment]
so it has same name as the original ng-forum. -_- amanuel/ng-forum

**Comment by jdc20181** [comment]
lol i cant write when i sleep. I didnt say i was gonna go to sleep anyways lol 
No its Ng-Forum UserGuide

**Comment by jdc20181** [comment]
please explain your code on how it will work with my html i already have

**Comment by amanuel2** [comment]
ok then edit it here: https://www.gitbook.com/book/amanuel2/ng-forum

**Comment by amanuel2** [comment]
do i need to explain?

**Comment by amanuel2** [comment]
do i need to explain?

**Comment by amanuel2** [comment]
do i need to explain?

**Comment by amanuel2** [comment]
do i need to explain?

**Comment by jdc20181** [comment]
yes the code snippiet with the varible get element by id, that is how it is started and displays the information
im not kidding, the html code without the refresh button and the button to my guide on internet speed its 1 line.

**Comment by jdc20181** [comment]
its compact. Which is what I like. it is simplly a ID=Progress and that is that xD

**Comment by jdc20181** [comment]
here is the full snippet: '<h1 id="progress">JavaScript is turned off, or your browser is realllllly slow</h1>'

**Comment by jdc20181** [comment]
its suppose to be a h1 but i had to remove it the stupid github markdown

**Comment by amanuel2** [comment]
can we talk in gitter or slack? Talking in an issue page is like -_-

**Comment by amanuel2** [comment]
https://ng-forum.slack.com/messages/ Or https://ng-forum.slack.com/messages/

**Comment by jdc20181** [comment]
link???

**Comment by amanuel2** [comment]
ew

**Comment by amanuel2** [comment]
most commetned issue ever

**Comment by amanuel2** [comment]
most commetned issue ever

**Comment by amanuel2** [comment]
most commetned issue ever

**Comment by amanuel2** [comment]
most commetned issue ever

**Comment by amanuel2** [comment]
most commetned issue ever

**Comment by amanuel2** [comment]
most commetned issue ever

**Comment by amanuel2** [comment]
most commetned issue ever

**Comment by amanuel2** [comment]
most commetned issue ever

**Comment by jdc20181** [comment]
you have to add my email to the slack i cant access i t

**Pull request closed without merging**
